# Generated by Django 4.2.2 on 2023-06-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
